### PR TITLE
Search query builder

### PR DESCRIPTION
**Pull request by dnilasor**
Addressing [issue #28](https://github.com/dnilasor/quickgig/issues/28). Updated implementation of search that simplifies the combination of multiple parameters by utilizing SQLAlchemy's _and operator method and a list of filters created during SearchForm validation. 

Can you please check out this PR and edge test it by performing searches? I have done so but would like a second set of eyes before merging a significant change to the method

### CODE REVIEW

**Comment by dnilasor** [comment]
@ljaggy I am mainly talking to you I supposed because @jaymeyer2017 is taking the final tomorrow and you may look at this and/or want to update the app prior. Let's get this merged if it is solid!

**Comment by dnilasor** [comment]
@ljaggy in case I forget to say this tomorrow, if/when we end up merging this, I think it might be good to figure out a way to let people know in a non-ugly way that the date param searches for gigs that start on **or after** the date selected

**Comment by ljaggy** [comment]
Sounds good. I'll test tonight when I get home to my laptop and will let
you know. If we merge, I'll probably add some kind of small note about date
search parameters on the page. Or maybe we could update the alert message
to say this? I'll think on this.

**Comment by jaymeyer2017** [comment]
This branch looks really nice!! Thanks to you both!! So much better!

Thanks - please go ahead and merge.

**Pull request merged**
